trigger:
  branches:
    include:
      - main
  paths:
    include:
      - '*'
      - '/bot/*'
      - '/internal/*'
      - 'pipelines/build-wordle-bot.yml'
    exclude:
      - 'pipelines/terraform-infra.yml'
      - 'terraform/*'

pool:
   vmImage: 'ubuntu-latest'

variables:
  - name: goVersion
    value: 1.19
  - name: serviceConnection
    value: WordleBot
  - name: webApp
    value: WordleBotApp

steps: 
- task: GoTool@0
  displayName: Install Go
  inputs:
    version: ${{ variables.goVersion }}
    
- task: Go@0
  displayName: Go Get
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)/cmd/bot'
 
- task: Go@0
  displayName: Go Build
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/cmd/bot'

- task: Go@0
  displayName: Go Test
  inputs:
    command: 'test'
    arguments: '-v'
    workingDirectory: '$(System.DefaultWorkingDirectory)/cmd/bot'


- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: WordleBot

 - task: Bash@3
   displayName: ls
   inputs:
     workingDirectory: '$(Build.ArtifactStagingDirectory)'
     targetType: 'inline'
     script: |
       ls

- task: AzureWebApp@1
  displayName: Publish App
  inputs:
    azureSubscription: ${{ variables.serviceConnection }}
    appType: 'webAppLinux'
    appName: ${{ variables.webApp }}
    package: '$(Build.ArtifactStagingDirectory)'
