trigger: 
 - main

pool:
   vmImage: 'ubuntu-latest'
   
steps: 
- task: GoTool@0
  displayName: Install Go
  inputs:
    version: '1.19'
    
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)/cmd/bot'
 
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)/cmd/bot'

- task: Go@0
  inputs:
    command: 'test'
    arguments: '-v'
    workingDirectory: '$(System.DefaultWorkingDirectory)/cmd/bot'


- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: WordleBot
